package mhinecounter;

import Filter.removeTags;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laureae_sd2082
 */
public class MhineCont extends javax.swing.JFrame {

    int mhe = 0;
    List<String> list = new ArrayList();
    List<String> listRemove = new ArrayList();
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/BigData";

    //  Database credentials
    static final String USER = "root";
    static final String PASS = "";

    public Object[][] RetrieveData() {
        Object[][] data = new Object[mhe][4];
        Connection conn = null;
        Statement stmt = null;
        String retrieveQuery;
        retrieveQuery = String.format("SELECT * from `countwords`");
        try {
            int cols = 0;
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(retrieveQuery);
            System.out.println(rs);
            while (rs.next()) {
                data[cols][0] = rs.getInt("Id");
                data[cols][1] = rs.getString("Word");
                data[cols][2] = rs.getInt("Count");
                data[cols][3] = rs.getString("School");
                ++cols;
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            String checkQuery = "Select word from `test`";
        }
        return data;
    }

    /**
     * Creates new form MhineCont
     */
    public MhineCont() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOrig = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRemove = new javax.swing.JTextArea();
        jButtonRemove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        count = new javax.swing.JButton();
        Show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaOrig.setBackground(new java.awt.Color(0, 0, 255));
        jTextAreaOrig.setColumns(20);
        jTextAreaOrig.setForeground(new java.awt.Color(204, 255, 204));
        jTextAreaOrig.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOrig);

        jTextAreaRemove.setBackground(new java.awt.Color(0, 0, 255));
        jTextAreaRemove.setColumns(20);
        jTextAreaRemove.setForeground(new java.awt.Color(204, 255, 204));
        jTextAreaRemove.setRows(5);
        jScrollPane2.setViewportView(jTextAreaRemove);

        jButtonRemove.setText("Count");
        jButtonRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoveMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("Tags Remover");
        jLabel1.setMaximumSize(new java.awt.Dimension(69, 20));

        count.setText("Remove Tags");
        count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countActionPerformed(evt);
            }
        });

        Show.setText("Show");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(count)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonRemove)
                        .addGap(34, 34, 34)
                        .addComponent(Show)
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemove)
                    .addComponent(count)
                    .addComponent(Show))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoveMouseClicked
        jTextAreaRemove.setText("");
        String str = jTextAreaOrig.getText();
        removeTags f = new removeTags();
        str = f.removeHTML(str);
        str = str.replaceAll("\\s+", " ");
        String output = "";

        Connection conn = null;
        Statement stmt = null;
        try {
            //STEP 2: Register JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            //STEP 3: Open a connection
            System.out.println("Connecting to a selected database...");
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            System.out.println("Connected database successfully...");

            //STEP 4: Execute a query
            System.out.println("Inserting records into the table...");
            stmt = conn.createStatement();

            String[] loop = str.split(" ");
            for (String x : loop) {
                if (list.contains(x)) {
                    continue;
                } else {
                    list.add(x);
                }
            }
            
            list.remove(list.indexOf(""));
            for (String y : list) {
                int counter = 0;
                for (String z : loop) {
                    if (y.equals(z)) {
                        counter++;
                    }
                }
                output += (y + " = " + counter + "; \n");
                String sql = String.format("INSERT INTO countwords(Word,Count,School) VALUES ('%s','%d','%s')", y, counter, "USC");
                stmt.executeUpdate(sql);
                System.out.println("Inserted records into the table...");
                mhe++;
            }
            jTextAreaRemove.setText(output);

        } catch (SQLException se) {
            //Handle errors for JDBC
            se.printStackTrace();
        } catch (Exception e) {
            //Handle errors for Class.forName
            e.printStackTrace();
        } finally {
            //finally block used to close resources
            try {
                if (stmt != null) {
                    conn.close();
                }
            } catch (SQLException se) {
            }// do nothing
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException se) {
                se.printStackTrace();
            }//end finally try
        }//end try
        System.out.println("Goodbye!");


    }//GEN-LAST:event_jButtonRemoveMouseClicked

    private void countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countActionPerformed
        jTextAreaRemove.setText("");
        String str = jTextAreaOrig.getText();
        removeTags f = new removeTags();
        str = f.removeHTML(str);
        str = str.replaceAll("\\s+", " ");
        String output = "";

        String[] loop = str.split(" ");
        for (String x : loop) {
            if (listRemove.contains(x)) {
                continue;
            } else {
                listRemove.add(x);
            }
        }
        listRemove.remove(0);
        System.out.println(listRemove);
        for (String y : listRemove) {
            output += (y + "\n");
        }
        jTextAreaRemove.setText(output);
    }//GEN-LAST:event_countActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        final JFrame frame = new JFrame("JTable Demo");
        String[] columns = {"id", "word", "count", "school"};
        Object[][] data = RetrieveData();
        DefaultTableModel tableModel = new DefaultTableModel(data, columns) {
            public boolean isCellEditable(int row, int column) {
                //all ceisCellEditablells false
                return false;
            }
        };
        this.setVisible(false);
        JTable popUpTable = new JTable(data, columns);
        Font font = new Font("Verdana", Font.PLAIN, 12);
        popUpTable.setModel(tableModel);
        popUpTable.setFont(font);
        popUpTable.setRowHeight(25);
        popUpTable.getTableHeader().setPreferredSize(new Dimension(100, 30));
        popUpTable.getTableHeader().setFont(font);
        JOptionPane.showMessageDialog(null, new JScrollPane(popUpTable), "Word Count", JOptionPane.INFORMATION_MESSAGE
        );
        this.setVisible(true);
    }//GEN-LAST:event_ShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MhineCont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MhineCont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MhineCont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MhineCont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MhineCont().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Show;
    private javax.swing.JButton count;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaOrig;
    private javax.swing.JTextArea jTextAreaRemove;
    // End of variables declaration//GEN-END:variables
}
